### ISSUE TITLE
NullException when model responds

### ISSUE THREAD

**Issue by dr-graviton** [Azure-Samples/aoai-realtime-audio-sdk#86] opened 2024-11-18 20:30 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 1. Pull the latest code. 
2. Run dotnet/samples/console-from-mic
3. Say anything

### Any log messages given by the failure
>* Connecting to Azure OpenAI endpoint (AZURE_OPENAI_ENDPOINT): https://***.openai.azure.com/
 * Using API key (AZURE_OPENAI_API_KEY): cdcb3**
 * Using deployment (AZURE_OPENAI_DEPLOYMENT): gpt-4o-realtime-preview
 <<< Connected: session started
 >>> Listening to microphone input
 >>> (Just tell the app you're done to finish)

 <<< Start of speech detected @ 00:00:11.0400000
 <<< End of speech detected @ 00:00:11.5200000
 >>> USER: Hi.

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SpeakerOutput.EnqueueForPlayback(BinaryData audioData) in C:\sandbox\aoai-realtime-audio-sdk\dotnet\samples\console-from-mic\SpeakerOutput.cs:line 29
   at Program.Main(String[] args) in C:\sandbox\aoai-realtime-audio-sdk\dotnet\samples\console-from-mic\Program.cs:line 93
   at Program.Main(String[] args) in C:\sandbox\aoai-realtime-audio-sdk\dotnet\samples\console-from-mic\Program.cs:line 42
   at Program.<Main>(String[] args)

### Expected/desired behavior
> It should play the model output

### OS and Version?
> Windows 11

### Versions
>23H2

### Mention any other details that might be useful
This works fine on the commit: 9d5f53043030a4875e76511810b3100008bbdeb8
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by paulbatum** [comment] 2024-11-21 19:13
Dupe of #74 , you can work around it with a null check like so:

```csharp
if (deltaUpdate.AudioBytes != null)
{
    speakerOutput.EnqueueForPlayback(deltaUpdate.AudioBytes);
}
```

**Closed** 2024-11-25 20:01 UTC
